version: '3.5'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: modak/notification.api
    ports:
      - '8080:8080'
    depends_on:
      -  db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
